[Info][localhost][12/2/2015 5:55:48 PM]: Successfully connected to Core Server: localhost
[Error][localhost][12/3/2015 11:07:52 AM]: Cannot connect to Core server localhost Wrong credentials.
WCFClientBase.HttpUnauthorizedRequestException
Call to service method https://localhost:8006/apprecovery/api/core/agents/protected GET failed
   at WCFClientBase.ClientBase.HandleResponse(Uri uri, String method, HttpResponseMessage response)
   at WCFClientBase.ClientBase.GetResponse(Uri uri, String method, String knownEtag)
   at WCFClientBase.ClientBase.ExecuteServiceCall[T](Uri uri, String method, String knownETag)
   at Replay.Core.Client.AgentsManagementCoreClient.GetProtectedAgents()
   at ChangeGen_v2.CoreConnector.GetServersToListFromCore(CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Model\CoreConnector.cs:line 43
   at ChangeGen_v2.ServerWrapper.ServersToListView(ListView listview, CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Controller\ServerWrapper.cs:line 16
   at ChangeGen_v2.Form1.btn_Connect_Click(Object sender, EventArgs e) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\View\Form1.cs:line 47
[Error][localhost][12/3/2015 11:09:28 AM]: Cannot connect to Core server localhost Wrong credentials.
WCFClientBase.HttpUnauthorizedRequestException
Call to service method https://localhost:8006/apprecovery/api/core/agents/protected GET failed
   at WCFClientBase.ClientBase.HandleResponse(Uri uri, String method, HttpResponseMessage response)
   at WCFClientBase.ClientBase.GetResponse(Uri uri, String method, String knownEtag)
   at WCFClientBase.ClientBase.ExecuteServiceCall[T](Uri uri, String method, String knownETag)
   at Replay.Core.Client.AgentsManagementCoreClient.GetProtectedAgents()
   at ChangeGen_v2.CoreConnector.GetServersToListFromCore(CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Model\CoreConnector.cs:line 43
   at ChangeGen_v2.ServerWrapper.ServersToListView(ListView listview, CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Controller\ServerWrapper.cs:line 16
   at ChangeGen_v2.Form1.btn_Connect_Click(Object sender, EventArgs e) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\View\Form1.cs:line 47
[Error][localhost][12/3/2015 11:14:57 AM]: Cannot connect to Core server localhost Wrong credentials.
WCFClientBase.HttpUnauthorizedRequestException
Call to service method https://localhost:8006/apprecovery/api/core/agents/protected GET failed
   at WCFClientBase.ClientBase.HandleResponse(Uri uri, String method, HttpResponseMessage response)
   at WCFClientBase.ClientBase.GetResponse(Uri uri, String method, String knownEtag)
   at WCFClientBase.ClientBase.ExecuteServiceCall[T](Uri uri, String method, String knownETag)
   at Replay.Core.Client.AgentsManagementCoreClient.GetProtectedAgents()
   at ChangeGen_v2.CoreConnector.GetServersToListFromCore(CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Model\CoreConnector.cs:line 43
   at ChangeGen_v2.ServerWrapper.ServersToListView(ListView listview, CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Controller\ServerWrapper.cs:line 16
   at ChangeGen_v2.Form1.btn_Connect_Click(Object sender, EventArgs e) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\View\Form1.cs:line 45
[Error][localhost][12/3/2015 11:22:57 AM]: Cannot connect to Core server localhost Wrong credentials.
WCFClientBase.HttpUnauthorizedRequestException
Call to service method https://localhost:8006/apprecovery/api/core/agents/protected GET failed
   at WCFClientBase.ClientBase.HandleResponse(Uri uri, String method, HttpResponseMessage response)
   at WCFClientBase.ClientBase.GetResponse(Uri uri, String method, String knownEtag)
   at WCFClientBase.ClientBase.ExecuteServiceCall[T](Uri uri, String method, String knownETag)
   at Replay.Core.Client.AgentsManagementCoreClient.GetProtectedAgents()
   at ChangeGen_v2.CoreConnector.GetServersToListFromCore(CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Model\CoreConnector.cs:line 43
   at ChangeGen_v2.ServerWrapper.ServersToListView(ListView listview, CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Controller\ServerWrapper.cs:line 16
   at ChangeGen_v2.Form1.btn_Connect_Click(Object sender, EventArgs e) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\View\Form1.cs:line 45
[Error][localhost][12/3/2015 11:23:02 AM]: Cannot connect to Core server localhost Wrong credentials.
WCFClientBase.HttpUnauthorizedRequestException
Call to service method https://localhost:8006/apprecovery/api/core/agents/protected GET failed
   at WCFClientBase.ClientBase.HandleResponse(Uri uri, String method, HttpResponseMessage response)
   at WCFClientBase.ClientBase.GetResponse(Uri uri, String method, String knownEtag)
   at WCFClientBase.ClientBase.ExecuteServiceCall[T](Uri uri, String method, String knownETag)
   at Replay.Core.Client.AgentsManagementCoreClient.GetProtectedAgents()
   at ChangeGen_v2.CoreConnector.GetServersToListFromCore(CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Model\CoreConnector.cs:line 43
   at ChangeGen_v2.ServerWrapper.ServersToListView(ListView listview, CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Controller\ServerWrapper.cs:line 16
   at ChangeGen_v2.Form1.btn_Connect_Click(Object sender, EventArgs e) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\View\Form1.cs:line 45
[Info][localhost][12/3/2015 11:23:18 AM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 12:55:02 PM]: Successfully connected to Core Server: localhost
[Error][12][12/3/2015 1:23:22 PM]: Cannot connect to Core server 12
WCFClientBase.ClientServerErrorException
Call to service method https://0.0.0.12:8006/apprecovery/api/core/agents/protected GET failed
   at WCFClientBase.ClientBase.HandleServiceMethodCallException(Uri uri, String method, TimeSpan elapsedTime, Exception e)
   at WCFClientBase.ClientBase.ExecuteAction(HttpClient client, Uri uri, String method)
   at WCFClientBase.ClientBase.GetResponse(Uri uri, String method, String knownEtag)
   at WCFClientBase.ClientBase.ExecuteServiceCall[T](Uri uri, String method, String knownETag)
   at Replay.Core.Client.AgentsManagementCoreClient.GetProtectedAgents()
   at ChangeGen_v2.CoreConnector.GetServersToListFromCore(CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Model\CoreConnector.cs:line 43
   at ChangeGen_v2.ServerWrapper.ServersToListView(ListView listview, CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Controller\ServerWrapper.cs:line 16
   at ChangeGen_v2.Form1.btn_Connect_Click(Object sender, EventArgs e) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\View\Form1.cs:line 45
[Error][1233333333333333333333333333333333333333333][12/3/2015 1:23:41 PM]: Cannot connect to Core server 1233333333333333333333333333333333333333333
WCFClientBase.ClientServerErrorException
Call to service method https://1233333333333333333333333333333333333333333:8006/apprecovery/api/core/agents/protected GET failed
   at WCFClientBase.ClientBase.HandleServiceMethodCallException(Uri uri, String method, TimeSpan elapsedTime, Exception e)
   at WCFClientBase.ClientBase.ExecuteAction(HttpClient client, Uri uri, String method)
   at WCFClientBase.ClientBase.GetResponse(Uri uri, String method, String knownEtag)
   at WCFClientBase.ClientBase.ExecuteServiceCall[T](Uri uri, String method, String knownETag)
   at Replay.Core.Client.AgentsManagementCoreClient.GetProtectedAgents()
   at ChangeGen_v2.CoreConnector.GetServersToListFromCore(CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Model\CoreConnector.cs:line 43
   at ChangeGen_v2.ServerWrapper.ServersToListView(ListView listview, CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Controller\ServerWrapper.cs:line 16
   at ChangeGen_v2.Form1.btn_Connect_Click(Object sender, EventArgs e) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\View\Form1.cs:line 45
[Error][1233333333333333333333333333333333333333333][12/3/2015 1:25:54 PM]: Cannot connect to Core server 1233333333333333333333333333333333333333333
WCFClientBase.ClientServerErrorException
Call to service method https://1233333333333333333333333333333333333333333:8006/apprecovery/api/core/agents/protected GET failed
   at WCFClientBase.ClientBase.HandleServiceMethodCallException(Uri uri, String method, TimeSpan elapsedTime, Exception e)
   at WCFClientBase.ClientBase.ExecuteAction(HttpClient client, Uri uri, String method)
   at WCFClientBase.ClientBase.GetResponse(Uri uri, String method, String knownEtag)
   at WCFClientBase.ClientBase.ExecuteServiceCall[T](Uri uri, String method, String knownETag)
   at Replay.Core.Client.AgentsManagementCoreClient.GetProtectedAgents()
   at ChangeGen_v2.CoreConnector.GetServersToListFromCore(CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Model\CoreConnector.cs:line 43
   at ChangeGen_v2.ServerWrapper.ServersToListView(ListView listview, CoreConnectionCredentials coreCredentials) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\Controller\ServerWrapper.cs:line 16
   at ChangeGen_v2.Form1.btn_Connect_Click(Object sender, EventArgs e) in D:\Git_repos\DDTGenerator\DDTGenerator\ChangeGen_v2\ChangeGen_v2\View\Form1.cs:line 45
[Info][localhost][12/3/2015 1:26:21 PM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 1:47:04 PM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 1:47:45 PM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 1:52:25 PM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 1:53:43 PM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 1:54:12 PM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 1:54:45 PM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 1:58:34 PM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 2:03:35 PM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 2:07:27 PM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 2:12:23 PM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 2:15:58 PM]: Successfully connected to Core Server: localhost
[Info][localhost][12/3/2015 2:17:53 PM]: Successfully connected to Core Server: localhost
